name: Deploy Latest Docker Image
on:
  push:
    branches:
      - master
      - Feature-Issue-36
  release:
    types: [published]
jobs:
    Deploy_Latest_Docker:
      name: Deploy_Latest_Docker
      runs-on: ubuntu-latest
      steps:
      - name: run docker-compose up
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: sudo docker-compose up
          host: ${{ secrets.HOST }}
          username: bitnami
          passphrase: ${{ secrets.PASSPHRASE }}
          privateKey: ${{ secrets.PRIVATE_KEY }}
